{
 "title": "Spring Boot Micrometer Prometheus HTTP Client Requests",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "clientName",
    "query": {
     "query": "label_values(http_client_requests_seconds_count,client_name)"
    }
   },
   {
    "name": "uri",
    "query": {
     "query": "label_values(http_client_requests_seconds{client_name=\"$clientName\"},uri)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_count{client_name=\"$clientName\", uri=\"$uri\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_count{client_name=\"$clientName\", uri=\"$uri\"}[$__rate_interval])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_count{client_name=\"$clientName\", uri=\"$uri\", outcome!=\"SUCCESS\"}[$__rate_interval])) / sum(rate(http_client_requests_seconds_count{client_name=\"$clientName\", uri=\"$uri\"}[$__rate_interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(rate(http_client_requests_seconds_sum{client_name=\"$clientName\", uri=\"$uri\"}[$__rate_interval])) * 1000) / sum(rate(http_client_requests_seconds_count{client_name=\"$clientName\", uri=\"$uri\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(http_client_requests_seconds{client_name=\"$clientName\", uri=\"$uri\"}) by (quantile) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(http_client_requests_seconds{client_name=\"$clientName\", uri=\"$uri\"}) by (quantile) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}