{
 "title": "Spring Boot Micrometer Prometheus HTTP Server Requests",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "uri",
    "query": {
     "query": "label_values(http_server_requests_seconds_count,uri)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"$uri\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri=\"$uri\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"$uri\", outcome!=\"SUCCESS\"}[1m])) / sum(rate(http_server_requests_seconds_count{uri=\"$uri\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{uri=\"$uri\"}[1m])) / sum(rate(http_server_requests_seconds_count{uri=\"$uri\"}[1m])) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(http_server_requests_seconds{uri=\"$uri\"}) by (quantile) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(http_server_requests_seconds{uri=\"$uri\"}) by (quantile) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}